### ISSUE TITLE
Not able to run `make unit-sup` on mac native

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#1748]
Just trying to get a dev environment working on mac OS 10.12.2 following [this](https://github.com/habitat-sh/habitat/blob/master/BUILDING.md#mac-os-x-for-native-development) guidline.

Verifying correct working by running
```
make unit-sup
IN_DOCKER=false make unit-sup
```

The first one works while the second errors with:
```
(...)
   Compiling serde_derive v0.8.23
error: custom derive attribute panicked
  --> /Users/jcarter/projects/habitat-sh/habitat/components/core/src/package/ident.rs:25:10
   |
25 | #[derive(Deserialize, Serialize, Eq, PartialEq, Debug, Clone, Hash)]
   |          ^^^^^^^^^^^
   |
   = help: message: assertion failed: !p.is_null()

Build failed, waiting for other jobs to finish...
error: Could not compile `habitat_core`.

To learn more, run the command again with --verbose.
make: *** [unit-sup] Error 101
```
Very confused since I'm running the same version of cargo as in the container (identical hash)
```
~/projects/habitat-sh/habitat (master %=) % docker-compose run --rm shell cargo -V
Starting habitat_etc_1
Starting habitat_cache_artifacts_1
Starting habitat_cargo_1
Starting habitat_cache_keys_1
cargo 0.16.0-nightly (6e0c18c 2017-01-27)
~/projects/habitat-sh/habitat (master %=) % cargo -V
cargo 0.16.0-dev (6e0c18c 2017-01-27)
```

**Comment by bodymindarts** [comment]
Could be related to : https://github.com/serde-rs/serde/issues/613
Issue is resolved when using rustc current 1.17-nightly

**Comment by smurawski** [comment]
@bodymindarts as you noticed in #1818, we've just bumped all the serialization libs (serde, serde_json, and toml).  Would you be able to validate that this is still a problem?

**Comment by bodymindarts** [comment]
@smurawski I will have time to verify this weekend. No problem

**Comment by bodymindarts** [comment]
As of 25.02.2017 this is still an issue with rust-1.15.1. It seems that the library wasn't the root cause and / or rustc is also part of the issue and is fixed on rust nightly

**Comment by smurawski** [comment]
Thanks @bodymindarts, I'll try to replicate this coming week (dust off the mac..) and see if I can't track that failure reason down.

**Comment by bodymindarts** [comment]
This is old and constantly changing with every rustc / create version graph
