### ISSUE TITLE
hab sup --help and --version options return non zero

### ISSUE THREAD

**Issue by jtimberman** [habitat-sh/habitat#3480]
I'm filing this issue so it doesn't get lost - I brought this up in Slack today.

```
[3][default:/src:0]# hab sup --version
hab-sup 0.34.1/20171002020936
[4][default:/src:86]# echo $?
86
```

Also, this may be the underlying cause of #3147.

**Comment by reset** [comment]
@jtimberman we'll get this fixed up, thanks for finding it!

**Comment by rsertelon** [comment]
This has been fixed by upgrading CLAP in #4267

**Comment by raskchanky** [comment]
@rsertelon I'm not sure it has.  If I build both `hab` and `sup` on the current master branch I still get the results that @jtimberman did.

**Comment by rsertelon** [comment]
Hmm that is strange. I have definitely not the problem anymore :(

**Comment by raskchanky** [comment]
I believe the 86 comes from https://github.com/habitat-sh/habitat/blob/76fd606ce9f2335bac3938c4d33733ac807c32b5/components/launcher-protocol/src/lib.rs#L39 but I don't understand why the launcher is detecting an unsuccessful exit code from the supervisor when running `--version`.

**Comment by baumanj** [comment]
This was resolved by https://github.com/habitat-sh/habitat/pull/4918
